---
- name: apply common configuration to all nodes
  hosts: all
  user: root

  roles:
    - webserver
    - database

  vars:
    env:
      LANGUAGE: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_TYPE: en_US.UTF-8
